# Generated by Django 5.2.4 on 2025-07-19 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WORK', 'Work Experience'), ('EDU', 'Education')], max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('technologies', models.CharField(max_length=200)),
                ('project_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('github_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('LANG', 'Programming Language'), ('FRAME', 'Framework'), ('TOOL', 'Tool'), ('OTHER', 'Other')], max_length=5)),
                ('proficiency', models.PositiveIntegerField(default=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_class', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
